# Matching Individual Words

While the generate pipeline is usually sufficient, it's sometimes important to tailor stimuli more precisely. For instance, it may be important that a matched word is a plausible replacement for a target word in a sentence. The `match_word()` function exists for this purpose.

This function is currently more cumbersome to use than the generate pipeline, but might be updated to use similar tidyverse-style syntax in the future.

Here's an example usage of `match_word`, to suggest a word matched for "elephant" in terms of:

* Length (exactly)
* Frequency (within ±0.25 Zipf)
* Imageability (within ±1, on a 1-7 Likert rating scale)
* Part of Speech (i.e. is also a noun)

```{r, class='table'}
library(tidyverse)
library(LexOPS)

lexops %>%
  match_word(
    target = "elephant",
    list(
      "Length",
      c("Zipf.SUBTLEX_UK", -0.25, 0.25),
      c("IMAG.Glasgow_Norms", -1, 1),
      "PoS.SUBTLEX_UK"
    )
  ) %>%
  select(string, euclidean_distance, Length, Zipf.SUBTLEX_UK, IMAG.Glasgow_Norms, PoS.SUBTLEX_UK)
```

The suggested matches are returned in a dataframe, filtered to be within the specified tolerances, and ordered by euclidean distance from the target word (calculated using all the numeric variables used). The closest suggested match for "elephant" is "sandwich".
